spring:
  application:
    name: InventoryManagement
  thymeleaf:
    mode: HTML
    cache: false
  datasource:
    username: root
    password: 1408
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
server:
  port: 9090